language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t THIRUKUMARAN10/docker-react -f Dockerfile.dev .

script:
  - docker run THIRUKUMARAN10/docker-react npm run test -- --coverage 