language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t thirukumaran10/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true thirukumaran10/docker-react npm run test -- --coverage 